# src/OC/AdminBundle/Resources/config/routing.yml
oc_admin_homepage:
    path:     /
    defaults: { _controller: OCAdminBundle:Authentification:index }

oc_admin_appoinment_view:
    path:    /appoinments/{page} 
    defaults: { _controller: OCAdminBundle:Appoinment:view, page: 1 }
    requirements:
              page: \d*

oc_admin_appoinment_add:
    path:    /appoinment/add
    defaults: { _controller: OCAdminBundle:Appoinment:add }

oc_admin_appoinment_edit:
    path:   /appoinment/edit/{id}
    defaults: { _controller: OCAdminBundle:Appoinment:edit }  
    requirements:
              id: \d+

oc_admin_appoinment_delete:
    path:  /appoinment/delete/{id}
    defaults: { _controller: OCAdminBundle:Appoinment:delete }
    requirements:
              id: \d+ 

oc_admin_appoinment_undelete:
    path:  /appoinment/undelete/{id}
    defaults: { _controller: OCAdminBundle:Appoinment:undelete }
    requirements:
              id: \d+               

oc_admin_doctor_view:
    path:  /doctors/{page}
    defaults: { _controller: OCAdminBundle:Doctor:view, page: 1 }
    requirements:
             page: \d*

oc_admin_doctor_add:
    path:  /doctor/add
    defaults: { _controller: OCAdminBundle:Doctor:add }

oc_admin_doctor_delete:
    path: /doctor/delete/{id}
    defaults: { _controller: OCAdminBundle:Doctor:delete }
    requirements:
             id: \d*
oc_admin_doctor_undelete:
    path:  /doctor/undelete/{id}
    defaults: { _controller: OCAdminBundle:Doctor:undelete }
    requirements:
              id: \d+   
oc_admin_doctor_edit:
    path: /doctor/edit/{id}
    defaults: {_controller: OCAdminBundle:Doctor:edit }
    requirements:
             id: \d*

oc_admin_patient_view:
    path: /patients/{page}
    defaults: { _controller: OCAdminBundle:Patient:view , page: 1 }  
    requirements:
              page: \id*

oc_admin_patient_add:
    path:  /patient/add
    defaults: { _controller: OCAdminBundle:Patient:add }

oc_admin_patient_delete:
    path: /patient/delete/{id}
    defaults: { _controller: OCAdminBundle:Patient:delete }
    requirements:
             id: \d*
oc_admin_patient_undelete:
    path:  /patient/undelete/{id}
    defaults: { _controller: OCAdminBundle:Patient:undelete }
    requirements:
              id: \d+   
oc_admin_patient_edit:
    path: /patient/edit/{id}
    defaults: {_controller: OCAdminBundle:Patient:edit }
    requirements:
             id: \d*              

              
